#!/usr/bin/env node
// Reads .scribe.yml from the repo root and writes src/content/config.ts.
// This is the ONLY thing that couples this package to Scribe — everything
// else here is a plain Astro site. It has no dependency on the Scribe
// service itself (no network calls, no @scribe-cms/admin import): per
// ARCHITECTURE.md D3, a customer's site must keep building even if Scribe
// is completely down, so the only input is the .scribe.yml already
// committed to this repo.
//
// The field-type union mirrors packages/admin/src/lib/schema.ts's
// `FieldType` — that file can't be imported directly (it pulls in Next.js
// admin-app dependencies this static site has no business depending on),
// so keep this list in sync by hand if that one changes.
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { parse as parseYaml } from 'yaml';

const REPO_ROOT = process.cwd();
const SCHEMA_PATH = resolve(REPO_ROOT, '.scribe.yml');
const FIXTURE_SCHEMA_PATH = resolve(REPO_ROOT, 'fixtures/scribe.yml');
// Astro 5.6+ deprecated `src/content/config.ts` in favor of this path.
const OUTPUT_PATH = resolve(REPO_ROOT, 'src/content.config.ts');
const SITE_CONFIG_OUTPUT_PATH = resolve(REPO_ROOT, 'src/site-config.ts');

function readSchema() {
  // A real customer repo always has .scribe.yml committed (provisioning
  // writes it). This package's own repo checkout doesn't — falling back to
  // the bundled fixture schema keeps `npm run build`/`dev` from this
  // directory working (e.g. a monorepo-wide `turbo run build`) without a
  // separate step, producing a working build with zero content, same as
  // pointing it at any .scribe.yml with no matching content files yet.
  const path = existsSync(SCHEMA_PATH) ? SCHEMA_PATH : FIXTURE_SCHEMA_PATH;
  if (path === FIXTURE_SCHEMA_PATH) {
    console.log('[generate-config] no .scribe.yml at repo root — using fixtures/scribe.yml');
  }
  const raw = readFileSync(path, 'utf-8');
  const parsed = parseYaml(raw);
  if (!parsed || !Array.isArray(parsed.collections)) {
    throw new Error('.scribe.yml must have a top-level "collections" array');
  }
  return parsed;
}

function optionValue(option) {
  return typeof option === 'string' ? option : option.value;
}

/** Field type -> zod expression (as source text, since we're emitting TS). */
function zodExprForField(field) {
  let expr;
  switch (field.type) {
    case 'string':
    case 'text':
    case 'rich-text':
    case 'image':
    case 'file':
    case 'reference':
      expr = 'z.string()';
      break;
    case 'number':
      expr = 'z.number()';
      break;
    case 'boolean':
      expr = 'z.boolean()';
      break;
    case 'date':
      expr = 'z.coerce.date()';
      break;
    case 'select': {
      const values = (field.options ?? []).map(optionValue);
      expr = values.length > 0 ? `z.enum(${JSON.stringify(values)})` : 'z.string()';
      break;
    }
    // block, object, code, uuid, and anything unrecognized: no purpose-built
    // mapping yet, so don't block the build on it.
    default:
      expr = 'z.any()';
  }
  if (field.list) expr = `z.array(${expr})`;
  if (!field.required) expr = `${expr}.optional()`;
  return expr;
}

/**
 * `*-frontmatter` collections (and the unset default) are Markdown files
 * with a data/body split; anything else (`yaml`, `json`, ...) is a data
 * file with no separate body, e.g. form submissions.
 */
function isMarkdownFormat(format) {
  return format === undefined || format === 'yaml-frontmatter' || format === 'json-frontmatter' || format === 'toml-frontmatter';
}

function globPatternFor(collection) {
  return isMarkdownFormat(collection.format) ? '**/*.md' : '**/*.{yml,yaml,json}';
}

function generateCollection(collection) {
  // isBody fields are the Markdown body itself, not part of the
  // frontmatter — glob() exposes them via `body`/`render()`, not `data`.
  const dataFields = (collection.fields ?? []).filter((field) => !field.isBody);
  const fieldLines = dataFields.map((field) => `    ${JSON.stringify(field.name)}: ${zodExprForField(field)},`).join('\n');
  const pattern = globPatternFor(collection);

  return `const ${collection.name} = defineCollection({
  loader: glob({ pattern: ${JSON.stringify(pattern)}, base: ${JSON.stringify(`./${collection.path}`)} }),
  schema: z.object({
${fieldLines}
  }),
});`;
}

function main() {
  const schema = readSchema();
  if (schema.collections.length === 0) {
    throw new Error('.scribe.yml has no collections');
  }

  const collectionBlocks = schema.collections.map(generateCollection).join('\n\n');
  const exportEntries = schema.collections.map((c) => `  ${JSON.stringify(c.name)}: ${c.name},`).join('\n');

  const output = `// AUTO-GENERATED by scripts/generate-config.mjs from .scribe.yml.
// Do not edit by hand — regenerated on every build.
import { defineCollection, z } from 'astro:content';
import { glob } from 'astro/loaders';

${collectionBlocks}

export const collections = {
${exportEntries}
};
`;

  mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
  writeFileSync(OUTPUT_PATH, output, 'utf-8');
  console.log(`[generate-config] wrote ${OUTPUT_PATH} from ${schema.collections.length} collection(s)`);

  writeSiteConfig(schema);
}

/** A field looks price-like if its name suggests money — used to format it
 * as currency generically, without hardcoding any one customer's field
 * names. */
function isPriceField(field) {
  return field.type === 'number' && /price|cost|rate|fee/i.test(field.name);
}

/** A field looks like an "is this shown/active" toggle — used to filter a
 * catalog collection's list down to published entries generically. */
function isActiveFlagField(field) {
  return field.type === 'boolean' && /^(is)?active$|^(is)?published$|^visible$/i.test(field.name);
}

/**
 * Site identity (slug, Turnstile key, which collection the contact form
 * posts to) is per-customer, so provisioning (7.4) writes it as extra
 * top-level keys on the same committed .scribe.yml rather than a second
 * file — admin's own schema parser ignores unknown top-level keys, so this
 * doesn't affect the CMS side at all.
 *
 * The "catalog" collection (any collection that isn't the blog-shaped
 * `posts` collection and isn't the form collection — e.g. a lawn-care
 * site's service packages, a bakery's menu items) is detected generically
 * here so `src/pages/[collection]/*.astro` can render list/detail pages for
 * it, and the home page can show a teaser, without either page hardcoding
 * one customer's collection name or field names.
 */
function writeSiteConfig(schema) {
  const formCollection = schema.collections.find((c) => c.form === true);
  const catalogCollection = schema.collections.find(
    (c) => c.form !== true && c.name !== 'posts',
  );

  const slug = schema.site ?? 'local-fixture';
  const siteName = schema.siteName ?? 'This Site';
  const turnstileSiteKey = schema.turnstileSiteKey ?? 'dev-mock-key';
  const contactCollection = schema.contactCollection ?? formCollection?.name ?? 'inquiries';

  // Internal/bookkeeping fields on the form collection (workflow status,
  // submission timestamp, ...) shouldn't become inputs on the public form —
  // everything else the schema declares is fair game.
  const skipContactFields = new Set(['status', 'createdAt', 'notes']);
  const contactFields = (formCollection?.fields ?? [])
    .filter((f) => !f.isBody && !skipContactFields.has(f.name))
    .map((f) => f.name);

  const catalogDataFields = (catalogCollection?.fields ?? []).filter((f) => !f.isBody);
  const catalogFields = catalogDataFields.map((f) => ({
    name: f.name,
    label: f.label ?? f.name,
    type: f.type,
  }));
  const catalogPriceField = catalogDataFields.find(isPriceField)?.name ?? null;
  const catalogActiveField = catalogDataFields.find(isActiveFlagField)?.name ?? null;
  const catalogSortField = catalogCollection?.view?.sort ?? null;
  const catalogTitleField = catalogCollection?.view?.primary ?? 'title';
  const catalogBodyField = catalogCollection?.fields?.find((f) => f.isBody)?.name ?? null;

  const output = `// AUTO-GENERATED by scripts/generate-config.mjs from .scribe.yml.
// Do not edit by hand — regenerated on every build.
export const SITE_SLUG = ${JSON.stringify(slug)};
export const SITE_NAME = ${JSON.stringify(siteName)};
export const TURNSTILE_SITE_KEY = ${JSON.stringify(turnstileSiteKey)};
export const CONTACT_COLLECTION = ${JSON.stringify(contactCollection)};
export const CONTACT_FIELDS = ${JSON.stringify(contactFields)};

export const CATALOG_COLLECTION = ${JSON.stringify(catalogCollection?.name ?? null)};
export const CATALOG_LABEL = ${JSON.stringify(catalogCollection?.label ?? catalogCollection?.name ?? null)};
export const CATALOG_FIELDS = ${JSON.stringify(catalogFields)};
export const CATALOG_TITLE_FIELD = ${JSON.stringify(catalogTitleField)};
export const CATALOG_BODY_FIELD = ${JSON.stringify(catalogBodyField)};
export const CATALOG_PRICE_FIELD = ${JSON.stringify(catalogPriceField)};
export const CATALOG_ACTIVE_FIELD = ${JSON.stringify(catalogActiveField)};
export const CATALOG_SORT_FIELD = ${JSON.stringify(catalogSortField)};
`;

  writeFileSync(SITE_CONFIG_OUTPUT_PATH, output, 'utf-8');
  console.log(`[generate-config] wrote ${SITE_CONFIG_OUTPUT_PATH}`);
}

main();
